### ISSUE TITLE
require the module

### ISSUE THREAD

**Issue by louptheron** [freedomjs/freedom-port-control#6]
Hi,

stupid question... but how do I require this module ?

I `npm install --save` and `npm install --dev`

`Error: Cannot find module 'freedom-port-control'`

Thank you

**Comment by willscott** [comment]
This module doesn't define a main entry-point.
after [`npm install freedom-port-control`](https://www.npmjs.com/package/freedom-port-control)

you'll need to specify the actual entry point

``` javascript
var portcontrol = require('freedom-port-control/src/port-control');
```

this probably still won't work, since this code is meant to be run by freedom. to make that work, you'll need to install `freedom-for-node` and then

``` javascript
var freedom = require('freedom-for-node');
var portcontrol = freedom('node_modules/freedom-port-control/src/port-control.json');
```

**Comment by louptheron** [comment]
Thank you for the help.

There are some errors with dependencies (`bufferutil` and `utf-8-validate`) when `npm install freedom-for-node`, so not related to freedom. 
https://github.com/websockets/bufferutil/issues/22
